---
- name: Gather facts and display it
  hosts: rhel9
  tasks:
  - name: Display all gathered facts
    ansible.builtin.debug:
      var: ansible_facts

  - name: Display the currently running kernel version and distro
    ansible.builtin.debug:
      msg: "The kernel version is {{ ansible_facts.kernel }} and the distribution is {{ ansible_facts.distribution }}"