---
- name: Vars, conditions, and loops
  hosts: rhel9
  gather_facts: false
  vars:
    nums: 
      - 1
      - 10
      - 20
      - 25
  tasks:
    - name: Display any numbers larger than 10
      when: item > 10
      ansible.builtin.debug:
        msg: "{{ item}}"
      loop: "{{ nums }}"